### PR TITLE
Allow Spring v4

### LINKED ISSUE #27: Release version that supports 4.0 and above
I wanted to give this a try, but I'm getting this from bundler:

```
Bundler could not find compatible versions for gem "spring":
  In snapshot (Gemfile.lock):
    spring (>= 3.0.0)

  In Gemfile:
    spring

    spring-commands-rspec was resolved to 1.0.4, which depends on
      spring (>= 0.9.1)

    spring-watcher-listen was resolved to 2.0.0, which depends on
      spring (~> 1.2)
```

It looks like https://github.com/jonleighton/spring-watcher-listen/pull/26 addresses this, so could we get a release with it?

### PR DESCRIPTION
**Pull request by afdev82**
Fixes #27

### CODE REVIEW

**Comment by afdev82** [comment]
With Spring 4 I'm getting the following error if I try to run `bin/rake db:migrate` task:


```
/home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/spring-watcher-listen-1ff53e64b31f/lib/spring/watcher/listen.rb:59:in `+': no implicit conversion of Hash into Array (TypeError)
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/spring-watcher-listen-1ff53e64b31f/lib/spring/watcher/listen.rb:59:in `base_directories'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/spring-watcher-listen-1ff53e64b31f/lib/spring/watcher/listen.rb:26:in `start'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:81:in `start_watcher'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:90:in `preload'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:162:in `serve'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /home/antonio/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from -e:1:in `<main>'

```

I don't have this problem with Spring v3, so I think this gem is not compatible with Spring v4 yet.

**Comment by afdev82** [comment]
I've made some tests and I can confirm that I have the error only with Spring v4.0.0

I noticed that Spring v4 inserts

```
load File.expand_path('../spring', __FILE__)
```

instead of 

```
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
```

when I run the command to "springify" the executables in my bin/ directory (`bundle exec spring binstub --all`).
It's different from what Spring v3.1.1 did and from [here](https://github.com/rails/spring#setup).

Anyway I have the error already posted using both versions of the modified `bin/rake` with Spring v4.

**Comment by mxdavis** [comment]
👀

**Comment by justin808** [comment]
Any word on when this might get released?

**Comment by fcheung** [comment]
I believe i've fixed this in #32

**Comment by thilonel** [comment]
@afdev82 @fcheung looking forward for this update! :)

**Comment by afdev82** [comment]
@thilonel please refer to the PR #32 by @fcheung, thank you!

**Pull request closed without merging**
