### PR TITLE
Add listen 2 support.

### PR DESCRIPTION
**Pull request by cduez**
This solve https://github.com/jonleighton/spring-watcher-listen/issues/1.

All work was done here https://github.com/rails/spring/pull/194.

We are actually using it and everything is working as expected.

### CODE REVIEW

**Comment by e2** [comment]
Thanks for putting this together!

There's a few issues not related to the patches themselves, but I think this can be released anyway in the meantime.

The issues:
- there's a patch for the fork() problem in Celluloid, but it never got backported
- there's an upcoming optimized version of Listen 3.0, but it's not released yet
- there's a listen-compat library, which is supposed to wrap Listen, so that any version can be used

Anyway, thanks for moving this forward!

**Comment by e2** [comment]
@cduez - spring-watcher-listen released (2.0.0) and Listen is updated (3.0.0) - together they should work faster and without issues. (Let me know if you have any).

**Comment by cduez** [comment]
Thanks for the release and the update! I will test it asap.

**Comment by pjg** [comment]
This is awesome! No, it's even beyond awesome!

(PS: quick tests show that this works as intended)

**Comment by e2** [comment]
@pjg - thank @cduez for PR. 

Do report any issues you find with Listen 3.x, since it's a major, major rewrite.

**Comment by pjg** [comment]
Yes, thank you @cduez !

**Pull request merged**
